language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UGSwf0QRJ+ooHe+7vSlanVpJI1EDH7octrrvqcdkXnoWnQe5U2lZbKVYJ/fXgeAxE62y7LNEtobBQtBk+OxhQzOtZNxO8JeGHY7QOEL03m7XTFCaH6PAYl5npiS0ckv1n9TZwTvqXMqEkCAkBEJcm3iKHU2zHWPwYNUr9KVvqnI=
  file:
    - 'weasels.js'
    - 'weasels.min.js'
  on:
    tags: true
